### ISSUE TITLE
Horizontal scrollbar on an issue card

### ISSUE THREAD

**Issue by nknguyenhc** [CATcher-org/WATcher#371]
**Describe the bug**
There is a horizontal scrollbar found on an issue card.

**Screenshots**

![image](https://github.com/CATcher-org/WATcher/assets/87511888/e359660b-029a-47a7-bf56-a2dffd977bc0)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version: 1.2.2

**Additional context**
NIL

**Comment by nknguyenhc** [comment]
In `issue-pr-card-header.component.css`:

```css
.mat-card-title {
  display: flex;
  align-items: center;
  font-size: 12px;
  text-align: left;
  overflow: auto;
}
```

The `overflow: auto` property causes the scrollbar. This means that if there is an overflowing word, it causes the scrolling. Consider removing this property, and add the following properties:

```css
    word-break: break-all;
    width: 50px;
```
